- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- etc/customer.conf
- modules/config.py
https://github.com/ARGOeu/ARGO/issues/121
> VO jobs moved under customer's directory

- argo-egi-connectors.spec
- bin/migrate.py
https://github.com/ARGOeu/ARGO/issues/134
> migration script for new avro schema with map type

- argo-egi-connectors.spec
- bin/topology-gocdb-connector.py
https://github.com/ARGOeu/ARGO/issues/141
> changed internal parser structure to address entities with doubled scope

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/prefilter-egi.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- modules/writers.py
- generate meaningful statistic messages for every connector
- messages are written into syslog
https://github.com/ARGOeu/ARGO/issues/116
> meaningful output messages and improved logging of all connectors

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- modules/config.py
https://github.com/ARGOeu/ARGO/issues/170
> bugfix in case of no downtimes defined for given date

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- doc/sync.md
- etc/customer.conf
- modules/config.py
- bugfix handling lowercase defined POEM profiles
- remove hardcoded customer name for topology-gocdb-connector
https://github.com/ARGOeu/ARGO/issues/173
> configurable customer name  and bugfix for lowercased POEM profiles

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/prefilter-egi.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- cronjobs/poem
- cronjobs/topology-gocdb
- cronjobs/topology-vo
- cronjobs/weights
- doc/sync.md
- etc/global.conf
- modules/config.py
- modules/tools.py
- log failed VO and weights connections
https://github.com/ARGOeu/ARGO/issues/179
- added connection timeout for all connectors
- config files can be passed as arguments to every component 
https://github.com/ARGOeu/ARGO/issues/180
- added connection retry feature for all connectors
- prefilter explicit input and output
- reorganized prefilter global.conf
- DATE placeholder in global.conf so interpolation can be used
- prefilter poem_sync.out look back option
- remove obsoleted logging
- guide updated
- refactored connection retries
> connection timeouts, retries, config files as arguments

- README.md
- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- doc/sync.md
- modules/tools.py
- weights connector refactored
- README updated
https://github.com/ARGOeu/ARGO/issues/181
> README updated and weights connector refactored

- argo-egi-connectors.spec
- bin/poem-connector.py
- bin/prefilter-egi.py
- doc/sync.md
- modules/tools.py
- remove deprecated BaseException message
- poem-connector optional write of prefilter data
https://github.com/ARGOeu/ARGO/issues/184
> poem-connector optional write of prefilter data

- argo-egi-connectors.spec
- bin/migrate.py
- bin/topology-gocdb-connector.py
- etc/schemas/group_endpoints.avsc
- etc/schemas/group_groups.avsc
- etc/schemas/metric_profiles.avsc
> topology data without mixed int and string values

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- bin/weights-vapor-connector.py
- cronjobs/weights
- etc/global.conf
- modules/config.py
- modules/tools.py
- make use of VAPOR service for weights
- extended cert verification with CAfile bundle
/please review @themiszamani @skanct
> ARGO-546 switch from GSTAT to VAPOR service

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-gstat-connector.py
- cronjobs/weights
- etc/global.conf
- modules/config.py
- modules/tools.py
Reverts ARGOeu/argo-egi-connectors#73
> Revert "Version 1.5.0-1"

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/topology-gocdb-connector.py
- bin/weights-vapor-connector.py
- etc/poem-connector.conf
- modules/config.py
- modules/tools.py
- remove code for nagioses defined in obsoleted nagios-roles.conf
- catch JSON parse errors
- catch XML parse errors
/please review @themiszamani
> ARGO-584 Ensure to catch all exceptions of underlying library

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/poem-connector.py
- bin/prefilter-egi.py
- bin/topology-gocdb-connector.py
- bin/topology-vo-connector.py
- bin/weights-vapor-connector.py
- modules/helpers.py
- poem and output files as arguments to prefilter
- refactored filename datestamp creation
/please review @themiszamani
> Refactored filename datestamp creation

- argo-egi-connectors.spec
- bin/prefilter-egi.py
> prefilter datestamp needs to be extracted from arg tuple

- argo-egi-connectors.spec
- bin/prefilter-egi.py
> prefilter output datestamp with underscores

- argo-egi-connectors.spec
- bin/topology-gocdb-connector.py
> Filter endpoints whose groups are filtered in group of groups topology component

- argo-egi-connectors.spec
- bin/topology-gocdb-connector.py
- modules/config.py
> ARGO-713 Topology connector should be able to pick only particular NGI or site

- argo-egi-connectors.spec
- bin/weights-vapor-connector.py
> ARGO-762 Remove inspection logic of HEPSPEC factors for previous days

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/topology-gocdb-connector.py
> ARGO-766 Remove SRMv2 service type mapping

- argo-egi-connectors.spec
- bin/downtimes-gocdb-connector.py
- bin/topology-gocdb-connector.py
- modules/config.py
- modules/log.py
> ARGO-842 Connectors dedicated file logger

- modules/helpers.py
> exception messages in retries

- modules/config.py
- tests/test_config.py
> default caller for global parse

- bin/prefilter-egi.py
> correct logger module import

- bin/prefilter-egi.py
- modules/config.py
> prefilter fix

- bin/prefilter-egi.py
> prefilter change all datestamp arguments to stamp

- Dockerfile
- argo-egi-connectors.spec
- /var/lib/argo-connectors should have more permissive privileges
> ARGO-966 Lower state files permissions

- Dockerfile
- bin/topology-gocdb-connector.py
- tests/run-tests.sh
- tests/test_input.py
Reverts ARGOeu/argo-egi-connectors#149
> Revert "ARGO-2209 Pass PRIMARY_KEY of GOCDB service endpoint as a unique service endpoint identifier"

- Jenkinsfile
Add jenkisfile to run on pipeline with test step and package step for centos6 and centos7
> DEVOPS-98 Add jenkins file

- Jenkinsfile
- Pipfile
Introducing pipfile to egi - connectors to be able to have a reproducible environment
> DEVOPS-99 Add pipfile

- tests/sample-service_endpoint.xml
- tests/test_feed.py
* Work is done by the student on training: https://github.com/dinoTog/argo-egi-connectors/tree/dino-praksa-zad5-tests
> ARGO-3340  Unit testing of parsing of GOCDB service endpoint

- CHANGELOG.md
- argo-connectors.spec
- ARGO-4428 Parse horizontalService flag now under main service bucket
> Version 2.2.4
